version: '3.3'

networks:
  # enable connection with Traefik
  proxy:
    name: traefik-net
    external: true

services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup-server
    restart: unless-stopped
    environment:
      - PUID=1000 # Enter the UID of the user who should own the files here
      - PGID=100 # Enter the GID of the user who should own the files here
      - TZ=Europe/Athens # Enter your timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - 'path/to/local/backups:/backups'
      - 'path/to/local/database:/var/urbackup'
    ports:
      - 55413
      - 55414
      - 55415
      - 35623/udp
    logging:
      options:
        max-size: 1g
    networks:
      - proxy
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # Get the routes from http
      - "traefik.http.routers.urbackup.rule=Host(`sub.example.com`)"
      - "traefik.http.routers.urbackup.entrypoints=http"
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.urbackup.middlewares=redirect-to-https@docker"
      # Get the routes from https
      - "traefik.http.routers.urbackup-secured.rule=Host(`sub.example.com`)"
      - "traefik.http.routers.urbackup-secured.entrypoints=https"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.urbackup-secured.tls=true"
      - "traefik.http.routers.urbackup-secured.tls.certresolver=letsencrypt"
      - "traefik.http.services.urbackup.loadbalancer.server.port=55414"
